mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
server:
  build: .
  ports:
    - "8081:80"
  links:
    - "mongo"
  environment:
    - MONGO_URL=ds064649.mlab.com
    - MONGO_PORT=64649
    - MONGO_DB=impactasaurus
    - MONGO_USER=impactasaurus
    - MONGO_PASS=2fFpKMwHfA8a
graphiql:
  build: ./graphiql
  ports:
    - "8082:80"
  links:
    - "server:local-impactasaurus.com"
