mongo:
  image: mongo:latest
  ports:
    - "27017"
server:
  build: .
  ports:
    - "8080:80"
  links:
    - "mongo"
  environment:
    - MONGO_URL=mongo
    - MONGO_PORT=27017
    - MONGO_DB=impactasaurus
graphiql:
  build: ./graphiql
  ports:
    - "8081:80"
  links:
    - "server:local-impactasaurus.com"
